GET http://localhost:8081/api/modelo-pasteis

GET http://localhost:8081/api/modelo-pasteis/1
POST http://localhost:8081/api/modelo-pasteis
Content-Type: application/json

{
    "tamanho": "Grande",
    "valor": 50.0
}

PUT http://localhost:8081/api/modelo-pasteis/4
Content-Type: application/json

{
    "tamanho": "Grande",
    "valor": 50.0
}

DELETE http://localhost:8081/api/modelo-pasteis/4